# -*- coding: utf-8 -*-
"""TPI-OE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gWKA_Ep1O_8eQ7YOEafNyt01eSqFo0uI
"""
"""TRABAJO PRÁCTICO INTEGRADOR - ORGANIZACIÓN EMPRESARIAL
Simulador de Chatbot para Gestión de Vacaciones usando Máquina de Estados"""

#Importamos 'os' para verificar si los archivos CSV existen en la computadora
import os
#Importamos 'sys' para poder cerrar el programa limpiamente cuando el usuario escribe 'salir'
import sys
#Importamos 'datetime' para la robustez en la validación de fechas.
from datetime import datetime


#Archivos de Persistencia (Base de Datos simuladas en Excel)
BD_EMPLEADOS = "empleados.csv" #Archivo que contiene legajos, nombres y saldos 
BD_SOLICITUDES = "solicitudes.csv" #Archivo transaccional donde se guardan las solicitudes de vacaciones aprobadas

#Máquina de Estados
ESTADO_INICIO = 0 #El bot está esperando el saludo inicial (/start o hola)
ESTADO_LEGAJO = 1 #El bot está esperando y validando el legajo del empleado
ESTADO_DIAS = 2 #El bot está validando la cantidad de días solicitados
ESTADO_FECHA = 3 #El bot está capturando la fecha de inicio del descanso
ESTADO_CONFIRMACION = 4 #El bot espera el "SI" o "NO" final para impactar los cambios

#Inicializamos la variable de control en el estado cero (Es el punto de partida del BPMN)
estado_actual = ESTADO_INICIO

#Variables Temporales (las que van a ir guardando los datos a medida que el usuario avanza)
datos_usuario = {
    "legajo": "",
    "nombre": "",
    "saldo_dias": 0,
    "dias_pedidos": 0,
    "fecha_inicio": ""
}

#Lectura y Escritura de archivos (funciones auxiliares)

#Función auxiliar para validar que la fecha sea real
def validar_fecha(fecha_str):
  try:
    #Intenta convertir el texto en una fecha real
    datetime.strptime(fecha_str, "%d/%m/%Y")
    return True #Si la fecha es válida y existe en el calendario
  except ValueError:
    return False #Si la fecha ingresada no es válida, se muestra el error y devuelve False.

def buscar_empleado(legajo_buscado):
  #Si el archivo de empleados no existe, no se puede continuar con la validación del Legajo
  if not os.path.exists(BD_EMPLEADOS):
    print("[Bot]: Error: El archivo de empleados no existe.")
    return None
  #Abrimos el archivo en modo lectura ('r') y con codificación utf-8 para evitar problemas con caracteres especiales
  with open(BD_EMPLEADOS, mode= 'r', encoding= 'utf-8') as archivo:
    #Leemos todas las líneas del archivo y las guardamos en una lista
    lineas = archivo.readlines()
  #Recorremos la lista desde el índice 1 en adelante para saltear la cabecera (fila de títulos)
  for linea in lineas[1:]: #Esto para poder saltear la primera línea de la tabla (cabecera)
    datos = linea.strip().split(",")#.strip() para eliminar saltos de línea y espacios, .split(",") para separar los campos por comas
    if datos[0] == legajo_buscado:
      return {
          "nombre": datos[1],
          "saldo": int(datos[2]) #Convertimos el saldo de días a entero para poder hacer las operaciones luego
      }
  #Si terminó el recorrido del bucle y no encontró el legajo, devolvemos None para indicar que no existe ese empleado en la base de datos
  return None 

def guardar_solicitud_y_saldo(legajo, nombre, dias, fecha):
  #Parte 1: Modificar saldo en empleados.csv
  with open(BD_EMPLEADOS, mode= 'r', encoding= 'utf-8') as archivo:
    lineas = archivo.readlines()
  #Inicializamos la lista incluyendo la cabecera (línea 0) para no perderla al escribir el nuevo archivo
  nuevas_lineas_empleados = [lineas[0]]  # Incluimos la cabecera
  #Recorremos los registros reales (del índice 1 en adelante)
  for linea in lineas[1:]:
    datos = linea.strip().split(",")
    #Si es el legajo del empleado que hizo la solicitud:
    if datos[0] == legajo:
      #Calculamos el nuevo saldo restando los días solicitados del saldo actual (que está en datos[2])
      nuevo_saldo = int(datos[2]) - dias
      #Creamos una nueva línea con el mismo formato pero con el saldo actualizado
      linea_modificada = f"{legajo}, {nombre}, {nuevo_saldo}\n"
      #Agregamos la línea modificada a la lista de nuevas líneas que vamos a escribir en el archivo
      nuevas_lineas_empleados.append(linea_modificada)
    else:
      #Si no es el legajo del empleado que hizo la solicitud, simplemente agregamos la línea original sin modificar a la lista de nuevas líneas
      nuevas_lineas_empleados.append(linea)

  #Abrimos el archivo en modo escritura ('w') para poder sobreescribirlo con los nuevos datos (incluyendo el saldo actualizado del empleado que hizo la solicitud)
  with open(BD_EMPLEADOS, mode= 'w', encoding= 'utf-8') as archivo:
    archivo.writelines(nuevas_lineas_empleados)

  #Parte 2: Registrar la solicitud en solicitudes.csv
  id_solicitud = 1 #Por defecto el primer ID es 1
  #Si el archivo de solicitudes ya existe, contamos cuántas líneas tiene para autogenerar el ID de la nueva solicitud.
  if os.path.exists(BD_SOLICITUDES):
    with open(BD_SOLICITUDES, mode= 'r', encoding= 'utf-8', newline='') as archivo:
      id_solicitud = len(archivo.readlines())
  #Creamos una nueva línea con el formato requerido para registrar la solicitud aprobada que se va a insertar debajo de todo (en la base de datos solicitudes.csv)
  nueva_fila = f"{id_solicitud},{legajo},{nombre},{dias},{fecha},APROBADO\n"
  #Si el archivo de solicitudes no existe o está vacío, escribimos la cabecera correspondiente antes de agregar la nueva solicitud.
  if not os.path.exists(BD_SOLICITUDES) or os.stat(BD_SOLICITUDES).st_size == 0:
    with open(BD_SOLICITUDES, mode= 'a', encoding= 'utf-8') as archivo:
      archivo.write("id_solicitud,legajo,nombre,dias_solicitados,fecha_inicio,estado\n")
  #Finalmente, abrimos el archivo de solicitudes en modo 'append' ('a') para agregar la nueva solicitud al final del archivo sin borrar las anteriores.
  with open(BD_SOLICITUDES, mode= 'a', encoding= 'utf-8', newline='') as archivo:
    archivo.write(nueva_fila)


#-----Controlador del Flujo de la Máquina de Estados-----
def procesar_chatbot(entrada):
  #Declaramos las variables globales para poder modificar su valor en todo el programa.
  global estado_actual, datos_usuario
  #.strip() para eliminar espacios en blanco al inicio y al final de la entrada del usuario.
  entrada = entrada.strip()

  #--PASO 0: Inicio--
  if estado_actual == ESTADO_INICIO:
    if entrada.lower() == "/start" or entrada.lower() == "hola":
      print("\n[Bot]: ¡Hola! Bienvenido/a al Asistente de Solicitud de Vacaciones.")
      print("[Bot]: Por favor, ingrese su número de legajo (Ej: 1001):")
      #Cambiamos el estado actual a ESTADO_LEGAJO para que en la próxima iteración del bucle el programa sepa que tiene que validar el legajo ingresado por el usuario.
      estado_actual = ESTADO_LEGAJO
    else:
      print("\n[Bot]: Escribí '/start' o 'hola' para iniciar el proceso de solicitud.")

  #--PASO 1: Validar Legajo (Compuerta 1 del BPMN)--
  elif estado_actual == ESTADO_LEGAJO:
    #Llamamos a la función encargada de leer el archivo empleados.csv
    empleado = buscar_empleado(entrada)
    #Si el objeto empleado no es None, significa que se encontró un registro con el legajo ingresado por el usuario y se puede continuar con el proceso.
    if empleado is not None:
      #Guardamos los datos del empleado en la variable temporal datos_usuario para poder usarlos en los siguientes pasos del proceso.
      datos_usuario["legajo"] = entrada
      datos_usuario["nombre"] = empleado["nombre"]
      datos_usuario["saldo_dias"] = empleado["saldo"]

      print(f"\n[Bot]: Empleado verificado: {empleado['nombre']}.")
      print(f"[Bot]: Tu saldo actual es de {empleado['saldo']} días.")
      #Compuerta Condicional: Si el saldo de días es menor o igual a 0, el proceso no puede continuar y se vuelve al estado inicial.
      if empleado["saldo"] <=0:
        print("[Bot]: No tenés días disponibles. Fin del proceso.")
        #Camino infeliz: Reiniciamos la máquina de estados al punto de partida.
        estado_actual = ESTADO_INICIO
      else:
        #Camino feliz: Solicitamos la cantidad de días y avanzamos al siguiente estado para validar esa información.
        print("\n[Bot]: ¿Cuántos días te querés tomar de vacaciones? (Ingresá solo números):")
        estado_actual = ESTADO_DIAS
    else:
      #Si el legajo no existe, se ejecuta la excepción y permanece en el mismo estado.
      print("\n[Bot]: El legajo no existe en la Base de Datos. Intente nuevamente:")

  #--PASO 2: Validar cantidad de días (Compuerta 2)--
  elif estado_actual == ESTADO_DIAS:
    if not entrada.isdigit():
      print("\n[Bot]: Entrada inválida. Por favor, ingrese un número entero:")
      return #Cortamos la función aquí para que vuelva a intentar en este mismo estado sin avanzar al siguiente paso.

    cantidad = int(entrada)
    saldo_disponible = datos_usuario["saldo_dias"]
  
    #Control de reglas de negocio
    if cantidad <= 0:
      print("\n[Bot]: La cantidad debe ser mayor a 0. Intentá de nuevo:")
    elif cantidad <= saldo_disponible:
      #Si la cantidad es válida y menor o igual al saldo disponible, guardamos esa información en la variable temporal datos_usuario para utilizarla en los siguientes pasos del proceso.
      datos_usuario["dias_pedidos"] = cantidad
      print("\n[Bot]: Ingresá la fecha en que querés arrancar (Formato: DD/MM/AAAA)")
      #Avanzamos al estado de captura de fechas para que el usuario pueda ingresar esa información en la próxima iteración del bucle.
      estado_actual = ESTADO_FECHA
    else:
      #Si pide más de lo que tiene, se activa la compuerta de rechazo por saldo insuficiente.
      print(f"\n[Bot]: Saldo insuficiente. Tenés {saldo_disponible} días disponibles pero pediste {cantidad}.")
      print("[Bot]: Por favor, ingresá una cantidad válida:")

  #--PASO 3: Capturar Fecha--
  elif estado_actual == ESTADO_FECHA:
    #Llamado a la función de validación de fecha
    if not validar_fecha(entrada):
      print("\n[Bot]: ERROR: La fecha ingresada no es válida o no existe en el calendario.")
      print("[Bot]: Por favor, use el formato DD/MM/AAAA (Ej: 19/06/2026):")
      return #Mantiene al usuario en este paso hasta que ingrese una fecha válida.
    
    #Si pasa la validación, continúa el flujo feliz original:
    datos_usuario["fecha_inicio"] = entrada
    print("\n" + "="*40)
    print("RESUMEN DE TU SOLICITUD")
    print("="*40)
    print(f"Empleado: {datos_usuario['nombre']}")
    print(f"Días solicitados: {datos_usuario['dias_pedidos']}")
    print(f"Fecha de inicio: {datos_usuario['fecha_inicio']}")
    print("="*40)
    print("[Bot]: ¿Los datos son correctos? (Respondé 'SI' o 'NO'):")
    #Avanzamos al estado definitivo de confirmación para que el usuario pueda revisar su solicitud y decidir si quiere registrarla o cancelarla.
    estado_actual = ESTADO_CONFIRMACION

  #--PASO 4: Registrar y Cerrar--
  elif estado_actual == ESTADO_CONFIRMACION:
    #Convertimos la respuesta del usuario a mayúscula para facilitar la comparación y evitar errores por mayúsculas/minúsculas.
    if entrada.upper() == "SI":
      #Invocamos la función de persistencia a la que le pasamos los datos necesarios para que registre la solicitud aprobada en solicitudes.csv y actualice el saldo del empleado en empleados.csv.
      guardar_solicitud_y_saldo(datos_usuario["legajo"], datos_usuario["nombre"], datos_usuario["dias_pedidos"], datos_usuario["fecha_inicio"])
      print("\n[Bot]: Solicitud registrada de forma exitosa en solicitudes.csv y saldo actualizado.")
      print("[Sistema]: Proceso completado. Sesión cerrada.")
      #Reiniciamos la máquina para que otro empleado pueda usar la consola.
      estado_actual = ESTADO_INICIO
    elif entrada.upper() == "NO":
      print("\n[Bot]: Trámite cancelado por el usuario.")
      #Si dice que no, limpiamos el flujo y volvemos al inicio.
      estado_actual = ESTADO_INICIO
    else:
      print("\n[Bot]: Por favor, respondé únicamente 'SI' o 'NO':")

#---BUCLE PRINCIPAL DE CONSOLA---
#Estructura encargada de mantener el programa vivo simulando un chat entre el usuario y el chatbot.
if __name__ == '__main__':
  print("SIMULADOR CHATBOT ACTIVO. Escribí '/start' para iniciar o 'salir' para cerrar.")
  while True:
    try:
      #Capturamos la entrada del usuario en la consola y la guardamos en la variable 'texto' para luego procesarla con la función 'procesar_chatbot'.
      texto = input("\nTú: ")
      #Si el usuario decide escribir 'salir', el programa se cierra mostrando un mensaje de despedida.
      if texto.lower() == "salir":
        print("¡Hasta luego!")
        sys.exit()
      procesar_chatbot(texto)
    except KeyboardInterrupt:
      #Captura el comando de interrupción (Ctrl+C) para cerrar el programa de forma limpia y mostrar un mensaje de despedida.
      sys.exit()